name: Production Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Initial build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Setting up nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Configuring aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build

      - name: Compressing build files
        run: cd build && zip -r ../${{ github.event.repository.name }}-${{ github.sha }}.zip *

      - name: Uploading build files
        run: aws s3 cp ${{ github.event.repository.name }}-${{ github.sha }}.zip s3://prod-${{ vars.BUCKET_NAME }}/builds

      # - name: Upload to bucket ${{ vars.BUCKET_NAME }}
      #   run: aws s3 cp build/ s3://prod-${{ vars.BUCKET_NAME }} --recursive

  deploy:
    name: deployment
    runs-on: ubuntu-latest
    needs: setup
    steps:

    - name: Configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Uploading build files
      run: |
        aws s3 cp s3://prod-${{ vars.BUCKET_NAME }}/builds/${{ github.event.repository.name }}-${{ github.sha }}.zip .
        unzip ${{ github.event.repository.name }}-${{ github.sha }}.zip
        pwd
        ls -ltrh

    - name: Invalidate Cloudfront
      id: invalidate-cloudfront
      run: aws cloudfront create-invalidation --distribution-id "${{ vars.DISTRIBUTION_ID }}"  --path "/*"
