name: Build UI

on:
  # workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      branch:
        required: true
        type: string
      bucket:
        required: true
        type: string
      environment:
        required: true
        type: string

    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true


jobs:
  build:
    name: Pull Repository & Build
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    
    - name: Build UI
      id: build-ui
      run: npm run build

    - name: Upload to S3
      id: upload-s3
      # run: aws s3 sync build/* prod-${{ bucket }}
      run: aws s3 cp build/ s3://prod-${{ bucket }} --recursive

      # run: |
      #   docker build -f ${{ inputs.dockerfile }} -t $TAG_LATEST -t $TAG_VERSION --target ${{ inputs.target }} . \
      #   --build-arg ENVS=${{ secrets.envs }}
        
      #   docker push $TAG_LATEST
      #   docker push $TAG_VERSION
      #   echo "::set-output name=image::$TAG_VERSION"