name: Project Deploymenta
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pull Repository & Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.environment }}
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ap-southeast-1

      - name: Install Dependencies
        id: install-dependencies
        # run: npm install
        run: echo $PROJECT_NAME

      - name: Build Project
        id: build-project
        run: npm run build

      - name: jhlhlkjh
        id: asdads-2123
        run: echo ${{ vars.bucket }}

      - name: Upload to bucket ${{ vars.bucket }}
        id: upload-files
        # run: aws s3 cp build/ s3://prod${{ vars.bucket }} --recursive
        run: echo ${{vars.PROJECT_NAME}}

      - name: Invalidate Cloudfront
        id: invalidate-cloudfront
        run: aws cloudfront create-invalidation --distribution-id "${{ vars.distribution_id }}"  --path "/*"
