name: Production Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy in Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Build Project
        id: build-project
        run: npm run build

      - name: Compress Build Files
        id: compress-build
        run: cd build && zip -r ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.zip *

      - name: Upload to bucket ${{ vars.BUCKET_NAME }}
        id: upload-files
        run: aws s3 cp build/ s3://prod-${{ vars.BUCKET_NAME }} --recursive

      - name: Invalidate Cloudfront
        id: invalidate-cloudfront
        run: aws cloudfront create-invalidation --distribution-id "${{ vars.DISTRIBUTION_ID }}"  --path "/*"
