name: Production Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy in Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Build Project
        id: build-project
        run: npm run build

      - name: Upload to bucket ${{ vars.BUCKET }}
        id: upload-files
        run: aws s3 cp build/ s3://prod${{ vars.BUCKET }} --recursive

      - name: Invalidate Cloudfront
        id: invalidate-cloudfront
        run: aws cloudfront create-invalidation --distribution-id "${{ vars.DISTRIBUTION_ID }}"  --path "/*"
