name: Project Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    inputs:
      aws_region:
        required: true
        type: string
      branch:
        required: true
        type: string
      bucket:
        required: true
        type: string
      environment:
        required: true
        type: string
      distribution_id:
        required: true
        type: string
      project_name:
        required: true
        type: string

    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        requ]ired: true

jobs:
  build:
    name: Pull Repository & Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ap-southeast-1

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Build Project
        id: build-project
        run: npm run build

      - name: Upload to bucket ${{ inputs.bucket }}
        id: upload-files
        run: aws s3 cp build/ s3://prod-${{ inputs.bucket }} --recursive

      - name: Invalidate Cloudfront
        id: invalidate-cloudfront
        run: aws cloudfront create-invalidation --distribution-id "${{ inputs.distribution_id }}"  --path "/*"
