name: Staging Deployment

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-staging:
    name: Build Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Setting up nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present

      - name: Compressing artifact
        run: |
          cd build
          zip -r ../stg-${{ github.sha }}.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: stg-${{ github.sha }}
          path: stg-${{ github.sha }}.zip

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build-staging]
    environment: 'Staging'
    steps:

    - name: Configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: stg-${{ github.sha }}
    
    - name: Unzipping build files
      run: |
        unzip stg-${{ github.sha }}.zip -d ${{ github.event.repository.name }}-${{ github.sha }}

    - name: Uploading files to bucket ${{ vars.BUCKET_NAME }}
      run: aws s3 sync ${{ github.event.repository.name }}-${{ github.sha }}/ s3://${{ vars.BUCKET_NAME }}

    - name: Invalidate Cloudfront
      id: invalidate-cloudfront
      run: aws cloudfront create-invalidation --distribution-id "${{ vars.DISTRIBUTION_ID }}"  --path "/*"